### ISSUE TITLE
The use of Cloudflares Rocketscript breaks all JS in OxyGen

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#34] opened 2015-08-11 11:30 UTC
Reference:
http://kokensupport.varoystrand.se/viewtopic.php?f=16&t=32&start=40#p395

Solution, Add ´ data-cfasync="false"´ before ´src´
Reference:
https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-
https://support.cloudflare.com/hc/en-us/articles/200169436--How-can-I-have-Rocket-Loader-ignore-my-script-s-in-Automatic-Mode-

**Comment by Hard-One** [comment] 2015-08-28 15:41
Added this to the wiki and closing as it's not a bug.

**Closed as completed by Hard-One** 2015-08-28 15:41 UTC
